/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(1)
	var __weex_style__ = __webpack_require__(2)
	var __weex_script__ = __webpack_require__(3)

	__weex_define__('@weex-component/e94b6944e74f1b1fc24b89f342bced35', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})

	__weex_bootstrap__('@weex-component/e94b6944e74f1b1fc24b89f342bced35',undefined,undefined)

/***/ },
/* 1 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "classList": [
	    "row"
	  ],
	  "children": [
	    {
	      "type": "image",
	      "classList": [
	        "img"
	      ],
	      "style": {
	        "width": 690,
	        "height": 40
	      },
	      "attr": {
	        "src": function () {return this.image}
	      }
	    },
	    {
	      "type": "div",
	      "style": {
	        "flexDirection": "row"
	      },
	      "children": [
	        {
	          "type": "div",
	          "classList": [
	            "leftContainer"
	          ],
	          "children": [
	            {
	              "type": "text",
	              "classList": [
	                "price"
	              ],
	              "attr": {
	                "value": function () {return this.couponAmountDisplay}
	              }
	            }
	          ]
	        },
	        {
	          "type": "div",
	          "classList": [
	            "rightContainer"
	          ],
	          "children": [
	            {
	              "type": "text",
	              "classList": [
	                "title"
	              ],
	              "attr": {
	                "value": function () {return this.useDirection}
	              }
	            },
	            {
	              "type": "text",
	              "classList": [
	                "date"
	              ],
	              "attr": {
	                "value": function () {return (this.prefix) + (this.indateDate)}
	              }
	            }
	          ]
	        }
	      ]
	    }
	  ]
	}

/***/ },
/* 2 */
/***/ function(module, exports) {

	module.exports = {
	  "row": {
	    "backgroundColor": "#FFFFFF",
	    "marginTop": 30,
	    "marginLeft": 30,
	    "marginRight": 30,
	    "height": 262,
	    "width": 690
	  },
	  "img": {},
	  "leftContainer": {
	    "flex": 1,
	    "width": 200,
	    "alignItems": "center",
	    "justifyContent": "center"
	  },
	  "rightContainer": {
	    "flex": 2,
	    "alignItems": "center"
	  },
	  "price": {
	    "fontSize": 70,
	    "color": "#CFA767"
	  },
	  "title": {
	    "flex": 1,
	    "fontSize": 30,
	    "color": "#666666",
	    "marginTop": 40,
	    "marginRight": 30
	  },
	  "date": {
	    "fontSize": 26,
	    "color": "#999999",
	    "marginTop": 40,
	    "marginRight": 30,
	    "marginBottom": 30
	  }
	}

/***/ },
/* 3 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	module.exports = {
		data: function () {return {
			couponAmountDisplay: '',
			useDirection: '',
			indateDate: '',
			prefix: '有效期:\n',
			image: 'image.png'
		}}
	};}
	/* generated by weex-loader */


/***/ }
/******/ ]);