/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(1)
	var __weex_template__ = __webpack_require__(5)
	var __weex_style__ = __webpack_require__(6)
	var __weex_script__ = __webpack_require__(7)

	__weex_define__('@weex-component/6a4ba78d3bec08ba3383ee9f8c6ffd4e', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})

	__weex_bootstrap__('@weex-component/6a4ba78d3bec08ba3383ee9f8c6ffd4e',undefined,undefined)

/***/ },
/* 1 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(2)
	var __weex_style__ = __webpack_require__(3)
	var __weex_script__ = __webpack_require__(4)

	__weex_define__('@weex-component/yzt-button', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})


/***/ },
/* 2 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "classList": function () {return [this.type]},
	  "style": {
	    "width": function () {return this.width},
	    "height": function () {return this.height},
	    "borderRadius": function () {return (this.height) + ' / 2'}
	  },
	  "children": [
	    {
	      "type": "text",
	      "classList": [
	        "title"
	      ],
	      "attr": {
	        "value": function () {return this.title}
	      }
	    }
	  ]
	}

/***/ },
/* 3 */
/***/ function(module, exports) {

	module.exports = {
	  "default": {
	    "justifyContent": "center",
	    "alignItems": "center",
	    "backgroundColor": "#CFA767"
	  },
	  "title": {
	    "color": "#FFFFFF",
	    "fontSize": 40
	  }
	}

/***/ },
/* 4 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	module.exports = {
		data: function () {return {
			title: '',
			type: 'default',
			width: 480.0,
			height: 96.0
		}}
	};}
	/* generated by weex-loader */


/***/ },
/* 5 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "classList": [
	    "container"
	  ],
	  "children": [
	    {
	      "type": "image",
	      "classList": [
	        "img"
	      ],
	      "attr": {
	        "src": "http://gw.alicdn.com/tps/i2/TB1DpsmMpXXXXabaXXX20ySQVXX-512-512.png_400x400.jpg"
	      }
	    },
	    {
	      "type": "text",
	      "id": "textId",
	      "classList": [
	        "text"
	      ],
	      "style": {
	        "fontSize": 120
	      },
	      "events": {
	        "click": "onclick"
	      },
	      "attr": {
	        "value": "Hello World"
	      }
	    },
	    {
	      "type": "a",
	      "attr": {
	        "href": "http://g.tbcdn.cn/ali-wireless-h5/res/0.0.16/hello.js"
	      },
	      "children": [
	        {
	          "type": "text",
	          "style": {
	            "color": "#0000FF",
	            "marginTop": 40
	          },
	          "attr": {
	            "value": "Click me to see how 'A' element opens a new world."
	          }
	        }
	      ]
	    },
	    {
	      "type": "weex-button",
	      "classList": [
	        "button"
	      ],
	      "attr": {
	        "title": "确定"
	      },
	      "shown": function () {return this.shown}
	    },
	    {
	      "type": "yzt-button",
	      "attr": {
	        "title": "取消"
	      },
	      "style": {
	        "marginTop": 40
	      },
	      "events": {
	        "click": "cancelclick"
	      }
	    }
	  ]
	}

/***/ },
/* 6 */
/***/ function(module, exports) {

	module.exports = {
	  "container": {
	    "alignItems": "center"
	  },
	  "img": {
	    "width": 400,
	    "height": 400
	  },
	  "text": {
	    "color": "#FF0000",
	    "marginTop": 80
	  },
	  "button": {
	    "marginTop": 80,
	    "width": 480,
	    "height": 96
	  }
	}

/***/ },
/* 7 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	var dom = __weex_require__('@weex-module/dom');
	var modal = __weex_require__('@weex-module/modal');
	module.exports = {
	  data: function () {return {
	    shown: true
	  }},
	  methods: {
	    onclick: function onclick() {
	      var text = this.$el('textId');
	      var attr = text.attr;
	      var style = { 'color': 'green' };
	      console.log(text);
	      if (attr.value === 'Hello World') {
	        attr.value = 'Hello Weex';
	        style.color = 'green';
	        this.shown = false;
	      } else {
	        attr.value = 'Hello World';
	        style.color = 'red';
	        this.shown = true;
	      }
	      dom.updateAttrs(text, attr);
	      dom.updateStyle(text, style);
	    },
	    cancelclick: function cancelclick(arg, e) {
	      modal.confirm({ message: '是否取消?', okTitle: 'YES', cancelTitle: "NO" }, function (result) {
	        modal.toast({ 'message': '你点击了' + result, 'duration': 1 });
	      });
	    }
	  },
	  ready: function ready() {
	    var globalEvent = __weex_require__('@weex-module/globalEvent');
	    globalEvent.addEventListener("weex_hello_world_confirm", function (e) {
	      modal.toast({ 'message': 'success', 'duration': 1 });
	    });
	  }
	};}
	/* generated by weex-loader */


/***/ }
/******/ ]);