/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(1)
	var __weex_script__ = __webpack_require__(2)

	__weex_define__('@weex-component/3105dfd5d8461b908c95848ab72d57be', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	})

	__weex_bootstrap__('@weex-component/3105dfd5d8461b908c95848ab72d57be',undefined,undefined)

/***/ },
/* 1 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "style": {
	    "width": 750,
	    "height": 1206
	  },
	  "children": [
	    {
	      "type": "div",
	      "children": [
	        {
	          "type": "text",
	          "style": {
	            "fontSize": 40
	          },
	          "attr": {
	            "value": "progress"
	          }
	        },
	        {
	          "type": "text",
	          "attr": {
	            "value": function () {return this.progress}
	          }
	        }
	      ]
	    },
	    {
	      "type": "div",
	      "children": [
	        {
	          "type": "text",
	          "attr": {
	            "value": "result"
	          }
	        },
	        {
	          "type": "text",
	          "attr": {
	            "value": function () {return this.result}
	          }
	        }
	      ]
	    }
	  ]
	}

/***/ },
/* 2 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	module.exports = {
		data: function () {return {
			progress: '',
			result: ''
		}},
		methods: {},
		ready: function ready() {
			var stream = __weex_require__('@weex-module/stream');
			stream.fetch({
				method: 'GET',
				url: 'http://jsfiddle.net/echo/jsonp/?callback=anything&result=content_in_response',
				type: 'jsonp'
			}, function (response) {
				console.log(response);
				this.result = response;
			}, function (response) {
				console.log(response);
				this.progress = response;
			});
		}
	};}
	/* generated by weex-loader */


/***/ }
/******/ ]);